name: Quality
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Cache node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [linters]
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Cache node-modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build
